#page title
page_title                                : YarnBuddy                                 # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : #1267678125                               # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : YarnBuddy                                 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A simple project tracker for knitters and crocheters.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Becky Hansmeyer                               
your_link                                 : https://www.beckyhansmeyer.com                     
your_city                                 : Nebraska                                
email_address                             : feedback@beckyhansmeyer.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : bhansmeyer
github_username                           : bhansmeyer
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Organize Your Projects
    description                           : Enter project details and add photos, notes, tags, and more.
    fontawesome_icon_name                 : tags
    
  - title                                 : Never Lose Your Place
    description                           : View pattern PDFs with adjustable markers and customizable row/stitch counters.
    fontawesome_icon_name                 : highlighter

  - title                                 : Track Your Stash
    description                           : Add photos and details about the yarn you own and sort by name, colorway, weight, and more.
    fontawesome_icon_name                 : archive

  - title                                 : Substitute and Convert
    description                           : Built-in calculators help you substitute yarns and convert between metric and imperial units.
    fontawesome_icon_name                 : balance-scale

  - title                                 : # Count From Your Wrist
    description                           : # YarnBuddy's companion Apple Watch app allows quick and easy access to all of your row counters.
    fontawesome_icon_name                 : # hand-point-up
  
  - title                                 : Choose Your Theme
    description                           : Go dark, stay light, or let the system decide.
    fontawesome_icon_name                 : adjust

  - title                                 : Never Miss An Occasion
    description                           : Set due dates for projects and be reminded at a time of your choosing (Pro only).
    fontawesome_icon_name                 : birthday-cake

  - title                                 : # Social Links
    description                           : # Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # link

  - title                                 : # FontAwesome Support
    description                           : # Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#21BDE5"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#7E42C1"
feature_icons_background_color            : "#F6EFFF"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
